###############################################################
#  Generated by:      Cadence Encounter 10.13-s272_1
#  OS:                Linux x86_64(Host ID eda25)
#  Generated on:      Sun Jan  1 17:05:50 2017
#  Design:            CHIP
#  Command:           saveDesign finish.enc
###############################################################
set sdc_version 1.4
current_design CHIP
set_propagated_clock  [get_ports {clk}]
set_drive 0.1  [get_ports {val}]
set_drive 0.1  [get_ports {dat[15]}]
set_drive 0.1  [get_ports {dat[14]}]
set_drive 0.1  [get_ports {dat[13]}]
set_drive 0.1  [get_ports {dat[12]}]
set_drive 0.1  [get_ports {dat[11]}]
set_drive 0.1  [get_ports {dat[10]}]
set_drive 0.1  [get_ports {dat[9]}]
set_drive 0.1  [get_ports {dat[8]}]
set_drive 0.1  [get_ports {dat[7]}]
set_drive 0.1  [get_ports {dat[6]}]
set_drive 0.1  [get_ports {dat[5]}]
set_drive 0.1  [get_ports {dat[4]}]
set_drive 0.1  [get_ports {dat[3]}]
set_drive 0.1  [get_ports {dat[2]}]
set_drive 0.1  [get_ports {dat[1]}]
set_drive 0.1  [get_ports {dat[0]}]
set_drive 0.1  [get_ports {clk}]
set_drive 0.1  [get_ports {rst}]
set_load -pin_load -max  20  [get_ports {done}]
set_load -pin_load -min  20  [get_ports {done}]
set_load -pin_load -max  20  [get_ports {freq[3]}]
set_load -pin_load -min  20  [get_ports {freq[3]}]
set_load -pin_load -max  20  [get_ports {freq[2]}]
set_load -pin_load -min  20  [get_ports {freq[2]}]
set_load -pin_load -max  20  [get_ports {freq[1]}]
set_load -pin_load -min  20  [get_ports {freq[1]}]
set_load -pin_load -max  20  [get_ports {freq[0]}]
set_load -pin_load -min  20  [get_ports {freq[0]}]
set_wire_load_model -library slow -max -name tsmc13_wl10
set_wire_load_model -library slow -min -name tsmc13_wl10
